Various fixes and improvements
DutchCodingCompany/pin_lock pull request #14
Opened 2023-02-21 13:39 UTC by minhdanh

Hi,
I've been working with this extension in the last few days and could made some minor improvements to it. Including:
- Support strong and weak biometric methods on new Android API. Reason is mentioned here: https://github.com/flutter/flutter/issues/107210#issuecomment-1178167791
- Fix availableMethods is not correctly set after app is resumed.
- Fix _checkInitialLockStatus method is called twice which may cause unwanted behaviors.

I also export biometric_availability.dart to use its classes outside of the package. Added a method isCorrectPin just for checking the PIN without touching the underlying data. The reason for these is because I didn't want to use the default AuthenticatorSetupWidget but used this package https://github.com/naoki0719/flutter_screen_lock. I just mainly used the authenticator for all the things: enabling/disable/changing PIN.

Please let me know if any of these changes make sense. Thank you!

2023-02-21 13:42 UTC, minhdanh commented on lib/src/entities/authenticator_impl.dart
> +  Future<bool> isCorrectPin({required Pin pin}) async {
The reason for this method is I use it when changing the PIN with my own passcode screen, and need a method to check if the current PIN is correct. I know there's a method named `unlockWithPin` that can be used but it would change the locking state and alter the data.

2023-02-21 13:44 UTC, minhdanh commented on lib/src/presentation/authenticator_widget.dart
> +    lockState = widget.authenticator.lockState;
This helps to ensure the method `_checkInitialLockStatus` of `lockState` not called twice, as we need it in line 125.

2023-02-21 13:46 UTC, minhdanh commented on lib/src/entities/authenticator_impl.dart
> +            _lockWithBiometricMethods();
I think the logic here should be the same with https://github.com/DutchCodingCompany/pin_lock/pull/14/files#diff-5c49c804fe2bc40c4001e93d44b185e624e5db9b53a68298ff3390eddc93b1d4R328 so I extracted it into a method called `_lockWithBiometricMethods()`

2023-02-21 14:55 UTC, Guldem requested changes

2023-02-21 14:55 UTC, Guldem commented on lib/src/entities/authenticator_impl.dart
> +  Future<bool> isCorrectPin({required Pin pin}) async {
Adding this method is a nice addition. But I think it should still follow the same rules as `unlockWithPin`. For example this method ignores maxRetries (technically its not unlocking). 

Without this mixing multiple method calls could possible cause weird behaviour.

2023-02-22 00:36 UTC, minhdanh commented on lib/src/entities/authenticator_impl.dart
> +  Future<bool> isCorrectPin({required Pin pin}) async {
Thank you. I updated the method. Please have a look.

2023-02-23 10:26 UTC, Guldem commented on lib/src/entities/authenticator_impl.dart
> +  Future<bool> isCorrectPin({required Pin pin}) async {
Thanks for the change!

2023-02-23 10:27 UTC, Guldem approved these changes
LGTM! Thanks for your contribution

2023-02-23 10:27 UTC, merged